#ifndef MNEMONICS_H_INCLUDED
#define MNEMONICS_H_INCLUDED

#define fetch(x)        buffer[x]
#define operand_1bytes  buffer[pc + 1]
#define operand_2bytes  buffer[pc + 1], buffer[pc + 2]
#define op_address      (buffer[pc + 2] << 8) | buffer[pc + 1]

#define ILLEGAL_OPCODE  "ERROR: Unknown opcode"

#define MOVAA   "MOV A, A"
#define MOVAB   "MOV A, B"
#define MOVAC   "MOV A, C"
#define MOVAD   "MOV A, D"
#define MOVAE   "MOV A, E"
#define MOVAH   "MOV A, H"
#define MOVAL   "MOV A, L"
#define MOVAM   "MOV A, M"

#define LDAXB   "LDAX B"
#define LDAXD   "LDAX D"
#define LDA     "LDA"

#define MOVBA   "MOV B, A"
#define MOVBB   "MOV B, B"
#define MOVBC   "MOV B, C"
#define MOVBD   "MOV B, D"
#define MOVBE   "MOV B, E"
#define MOVBH   "MOV B, H"
#define MOVBL   "MOV B, L"
#define MOVBM   "MOV B, M"

#define MOVCA   "MOV C, A"
#define MOVCB   "MOV C, B"
#define MOVCC   "MOV C, C"
#define MOVCD   "MOV C, D"
#define MOVCE   "MOV C, E"
#define MOVCH   "MOV C, H"
#define MOVCL   "MOV C, L"
#define MOVCM   "MOV C, M"

#define MOVDA   "MOV D, A"
#define MOVDB   "MOV D, B"
#define MOVDC   "MOV D, C"
#define MOVDD   "MOV D, D"
#define MOVDE   "MOV D, E"
#define MOVDH   "MOV D, H"
#define MOVDL   "MOV D, L"
#define MOVDM   "MOV D, M"

#define MOVEA   "MOV E, A"
#define MOVEB   "MOV E, B"
#define MOVEC   "MOV E, C"
#define MOVED   "MOV E, D"
#define MOVEE   "MOV E, E"
#define MOVEH   "MOV E, H"
#define MOVEL   "MOV E, L"
#define MOVEM   "MOV E, M"

#define MOVHA   "MOV H, A"
#define MOVHB   "MOV H, B"
#define MOVHC   "MOV H, C"
#define MOVHD   "MOV H, D"
#define MOVHE   "MOV H, E"
#define MOVHH   "MOV H, H"
#define MOVHL   "MOV H, L"
#define MOVHM   "MOV H, M"

#define MOVLA   "MOV L, A"
#define MOVLB   "MOV L, B"
#define MOVLC   "MOV L, C"
#define MOVLD   "MOV L, D"
#define MOVLE   "MOV L, E"
#define MOVLH   "MOV L, H"
#define MOVLL   "MOV L, L"
#define MOVLM   "MOV L, M"

#define MOVMA   "MOV M, A"
#define MOVMB   "MOV M, B"
#define MOVMC   "MOV M, C"
#define MOVMD   "MOV M, D"
#define MOVME   "MOV M, E"
#define MOVMH   "MOV M, H"
#define MOVML   "MOV M, L"

#define LXIB    "LXI B"
#define LXID    "LXI D"
#define LXIH    "LXI H"
#define LXISP   "LXI SP"
#define LHLD    "LHLD"
#define SHLD    "SHLD"
#define SPHL    "SPHL"

#define MVIA    "MVI A, "
#define MVIB    "MVI B, "
#define MVIC    "MVI C, "
#define MVID    "MVI D, "
#define MVIE    "MVI E, "
#define MVIH    "MVI H, "
#define MVIL    "MVI L, "
#define MVIM    "MVI M, "

#define STAXB   "STAX B"
#define STAXD   "STAX D"
#define STA     "STA "

#define ADDA    "ADD A, "
#define ADDB    "ADD B, "
#define ADDC    "ADD C, "
#define ADDD    "ADD D, "
#define ADDE    "ADD E, "
#define ADDH    "ADD H, "
#define ADDL    "ADD L, "
#define ADDM    "ADD M, "
#define ADI     "ADI "

#define ADCA    "ADC A, "
#define ADCB    "ADC B, "
#define ADCC    "ADC C, "
#define ADCD    "ADC D, "
#define ADCE    "ADC E, "
#define ADCH    "ADC H, "
#define ADCL    "ADC L, "
#define ADCM    "ADC M, "
#define ACI     "ACI "

#define SUBA    "SUB A, "
#define SUBB    "SUB B, "
#define SUBC    "SUB C, "
#define SUBD    "SUB D, "
#define SUBE    "SUB E, "
#define SUBH    "SUB H, "
#define SUBL    "SUB L, "
#define SUBM    "SUB M, "
#define SUI     "SUI "

#define SBBA    "SBB A, "
#define SBBB    "SBB B, "
#define SBBC    "SBB C, "
#define SBBD    "SBB D, "
#define SBBE    "SBB E, "
#define SBBH    "SBB H, "
#define SBBL    "SBB L, "
#define SBBM    "SBB M, "
#define SBI     "SBI "

#define DADB    "DAD B"
#define DADD    "DAD D"
#define DADH    "DAD H"
#define DADSP   "DAD SP"

#define DI      "DI"
#define EI      "EI"
#define NOP     "NOP"
#define HLT     "HLT"

#define INRA    "INR A, "
#define INRB    "INR B, "
#define INRC    "INR C, "
#define INRD    "INR D, "
#define INRE    "INR E, "
#define INRH    "INR H, "
#define INRL    "INR L, "
#define INRM    "INR M, "

#define DCRA    "DCR A, "
#define DCRB    "DCR B, "
#define DCRC    "DCR C, "
#define DCRD    "DCR D, "
#define DCRE    "DCR E, "
#define DCRH    "DCR H, "
#define DCRL    "DCR L, "
#define DCRM    "DCR M, "

#define INXB    "INX B"
#define INXD    "INX D"
#define INXH    "INX H"
#define INXSP   "INR SP"

#define DCXB    "DCX B"
#define DCXD    "DCX D"
#define DCXH    "DCX H"
#define DCXSP   "INR SP"

#define DAA     "DAA"
#define CMA     "CMA"
#define STC     "RTC"
#define CMC     "CMC"

#define RLC     "RLC"
#define RRC     "RRC"
#define RAL     "RAL"
#define RAR     "RAR"

#define ANAA    "ANA A, "
#define ANAB    "ANA B, "
#define ANAC    "ANA C, "
#define ANAD    "ANA D, "
#define ANAE    "ANA E, "
#define ANAH    "ANA H, "
#define ANAL    "ANA L, "
#define ANAM    "ANA M, "
#define ANI     "ANI "

#define XRAA    "XRA A, "
#define XRAB    "XRA B, "
#define XRAC    "XRA C, "
#define XRAD    "XRA D, "
#define XRAE    "XRA E, "
#define XRAH    "XRA H, "
#define XRAL    "XRA L, "
#define XRAM    "XRA M, "
#define XRI     "XRI "

#define ORAA    "ORA A, "
#define ORAB    "ORA B, "
#define ORAC    "ORA C, "
#define ORAD    "ORA D, "
#define ORAE    "ORA E, "
#define ORAH    "ORA H, "
#define ORAL    "ORA L, "
#define ORAM    "ORA M, "
#define ORI     "ORI "

#define CMPA    "CMP A, "
#define CMPB    "CMP B, "
#define CMPC    "CMP C, "
#define CMPD    "CMP D, "
#define CMPE    "CMP E, "
#define CMPH    "CMP H, "
#define CMPL    "CMP L, "
#define CMPM    "CMP M, "
#define CPI     "CPI "

#define JMP     "JMP"
#define JNZ     "JNZ"
#define JZ      "JZ"
#define JNC     "JNC"
#define JC      "JC"
#define JPO     "JPO"
#define JPE     "JPE"
#define JP      "JP"
#define JM      "JM"
#define PCHL    "PCHL"

#define CALL    "CALL"
#define CNZ     "CNZ"
#define CZ      "CZ"
#define CNC     "CNC"
#define CC      "CC"
#define CPO     "CPO"
#define CPE     "CPE"
#define CP      "CP"
#define CM      "CM"

#define RET     "RET"
#define RNZ     "RNZ"
#define RZ      "RZ"
#define RNC     "RNC"
#define RC      "RC"
#define RPO     "RPO"
#define RPE     "RPE"
#define RP      "RP"
#define RM      "RM"

#define RST0    "RST 0"
#define RST1    "RST 1"
#define RST2    "RST 2"
#define RST3    "RST 3"
#define RST4    "RST 4"
#define RST5    "RST 5"
#define RST6    "RST 6"
#define RST7    "RST 7"

#define PUSHB   "PUSH B"
#define PUSHD   "PUSH D"
#define PUSHH   "PUSH H"
#define PUSHPSW "PUSH PSW"
#define POPB    "POP B"
#define POPD    "POP D"
#define POPH    "POP H"
#define POPPSW  "POP PSW"

#define IN      "IN "
#define OUT     "OUT "

#endif // MNEMONICS_H_INCLUDED
